### ISSUE TITLE
Please explicitly include a license

### ISSUE THREAD

**Issue by lfam** [untitaker/pytest-subtesthack#1]
Can you include the full text of whatever software license you choose to release this under?

I saw in setup.py that the license is "MIT" but, unfortunately, that is ambiguous. "MIT" has been used to refer to both the X11 license and the Expat license: https://en.wikipedia.org/wiki/MIT_License#Various_versions

I am trying update the GNU Guix package of vdirsyncer, which depends on pytest-subtesthack. Without an explicit declaration of a software license, I can not include this package in Guix, and thus cannot update vdirsyncer to the newest version.

**Comment by untitaker** [comment]
re-released under the public domain.

**Comment by lfam** [comment]
Thank you for taking the time to clarify this.
