### ISSUE TITLE
Add `Framework :: Hypothesis` PyPI trove classifier

### ISSUE THREAD

**Issue by Zac-HD** [untitaker/pytest-subtesthack#2]
The Python Packaging Authority has recently created a new trove classifier to help users find Hypothesis-related packages, as described and demonstrated in HypothesisWorks/hypothesis#1663.

It would be great if this package used it too!

**Comment by Zac-HD** [comment]
Closing this as `pytest-subtesthack` is not really Hypothesis-specific.

**Comment by untitaker** [comment]
@Zac-HD if you make a PR I'll merge it. I think it's still related because hypothesis is the main usecase.
